version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432 # db postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbdelivery
    volumes:
      - pgdata:/data/postgres
  redisdb:
    image: redis
    container_name: Queue
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_PASSSWORD=docker
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSSWORD"
    volumes:
      - ./redis:/data/redis
  # app:
  #   build: .
  #   container_name: appDelivery
  #   ports:
  #     - 3000:3000 # application
  #     - 9229:9229 # debug
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - database
  #     - redisdb
  #   links:
  #     - redisdb
  #     - database

volumes:
  pgdata:
    driver: local
